<?php declare (strict_types= 1);
    // echo "sushma"
?>
<script type="text/x-magento-init">
   {
    "*":{
        "Magento_Ui/js/core/app": {
            "components": {
                "startSimple": { 
                    "component":"Sushma_KnockoutJs/js/plain-view-model"
                }
            }
        }
    }
   } 

</script>


<div data-bind="scope:'startSimple'">
<!-- <script>console.log("sushma soujanya ")</script> -->
   
    <h2 data-bind="text: title"></h2>
</div>
