<?php declare (strict_types= 1);
    // echo "sushma"
?>
<script type="text/x-magento-init">
   {
    "*":{
        "Magento_Ui/js/core/app": {
            "components": {
                "startSimple": { 
                    "component":"Sushma_KnockoutJs/js/plain-view-model",
                    "base_url": "<?= $block->escapeJs($block->getBaseUrl()) ?>"
                }
            }
        }
    }
   } 

</script>

<!-- 
<div data-bind="scope:'startSimple'"> -->
<!-- <script>console.log("sushma soujanya ")</script> -->
   <!-- <pre data-bind="text: output"></pre> -->
    <!-- <h2 data-bind="text: title"></h2> -->
    <!-- <pre data-bind="text: JSON.stringify(ccc,null,2)"></pre> -->
<!-- </div> -->
<div data-bind="scope: 'startSimple'">
    <!-- <ul data-bind='foreach : values'>
        <li data-bind="text: $data"></li> -->
    
   <!-- <table data-bind="foreach: exchange_rates"> -->
    <table>

        <tr>
            <th data-bind="i18n : 'Currency to'"></th>
            <th data-bind="i18n: 'Rate'"></th>
        </tr>
        <!-- ko foreach: exchange_rates-->
         <tr>
            <td data-bind="text:currency_to"></td>
            <td data-bind="text:rate"></td>
        </tr>
        <!-- /ko -->
   </table>

    <!-- </ul> -->
</div>