<div id='my-collapsible' data-mage-init='{"collapsible": {"active":true, "saveState":true}}'>
    <!-- we are telling that it is the collapsible title  with data-role -->
    <div data-role="title">
        <h2>How about a collapsible Widget?<button data-role='trigger'>GO</button></h2>
    </div>
    <!-- we are telling that it is the collapsible content with the data -role -content attribute-->
    <!-- <div data-role="content" style="display: none;"> -->
    <div data-role='content' id='example'>
        This is the collapsible content right here!
    </div>

</div>