<div data-mage-init='{"collapsible": {}}'>
    <!-- we are telling that it is the collapsible title  with data-role -->
    <div data-role="title">
        <h2>How about a collapsible Widget?</h2>
    </div>
    <!-- we are telling that it is the collapsible content with the data -role -content attribute-->
    <div data-role="content" style="display: none;">
        This is the collapsible content right here!
    </div>

</div>