<div id='my-collapsible' data-mage-init='{"collapsible": {"animate": {
        "duration" : 600,
        "easing" : "linear"
    }, "active":true, "saveState":true, "ajaxContent":true}}'>
    <!-- we are telling that it is the collapsible title  with data-role -->
    <div data-role="title">
        <h2>How about a collapsible Widget?<button data-role='trigger'>GO</button></h2>
    </div>
    <!-- we are telling that it is the collapsible content with the data -role -content attribute-->
    <!-- <div data-role="content" style="display: none;"> -->
    <div data-role='content' id='example'></div>
    <a href="<?= $block->getViewFileUrl("Sushma_JsUiComponents/js/example-content.html") ?>" data-ajax="true">

</div>