<?php
declare (strict_types=1);

?>
<!-- <h1 date-mage-init='{"Sushma/title":{}}'></h1> -->

<!-- <script type='text/x-magento-init'>
    {
        "#target" : {
            "coffee":{
                "base_url" : "<?= $block->escapeJs($block->getBaseUrl());?>"
            }
        }
    }
</script> 
<pre id='target'></pre> -->



<form data-mage-init='{"validation" : {}}'>
    <div class='control'>
        <input type='text' name='email' id='email' class='input-text' placeholder="<?=__('Your Email')?>"
             data-validate="{required : true ,'validate-email':true}"/>
    </div>
    <button type='submit' class='action primary'><?= __('Submit')?></button>
</form>